# Generated by Django 3.2 on 2021-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210424_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
