# Generated by Django 3.2 on 2021-04-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210417_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='event',
            name='uuid',
        ),
    ]
