# Generated by Django 3.2 on 2021-04-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210417_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='project_name',
            field=models.CharField(default='Bad ass project', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='events.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='events', serialize=False, to='events.contract'),
        ),
    ]
