# Generated by Django 3.2 on 2021-04-23 13:00

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group_name in ('sales', 'support'):
        group = Group(name=group_name)
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
