# Generated by Django 3.2 on 2021-04-24 06:27

from django.db import migrations


def create_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    group = Group(name="managers")
    group.save()
    for pk in list(range(29, 45)):
        permission = Permission.objects.get(pk=pk)
        group.permissions.add(permission)
    group.save()



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210423_1500'),
    ]

    operations = [
        migrations.RunPython(create_permissions),        
    ]
